# site properties and page defaults
title: mivlab-cbnu
subtitle: Machine Intelligence and Vision Laboratory @CBNU
socialtitle:  Biology and Cancer Regulatory Genomics Lab - Aziz Khan
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/banner.jpg
logo: images/logo.png
show-title: false
show-subtitle: true
logo-text: true

proofer: false
url: https://khanlab.io
baseurl:

# site social media and other links
links:
  email: contact@mivlab-cbnu.com
  orcid: 0000-0002-6459-6224
  google-scholar: m23RfrcAAAAJ&sortby=pubdate
  github: mivlab-cbnu
  # bluesky: khanlab.bio
  # twitter: khanaziz84
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
