- title: "Domain Adaptation Regression for AI Model under Non-linear and Continual Domain Shift"
  institution: "Chungbuk National University"
  period: "2025-2026"
  role: "Principal Investigator"
  group: completed

- title: "Development of Language‐Guided Cross‐Modal Domain Adaptation"
  institution: "Ewha Womans University"
  period: "2024-2025"
  role: "Principal Investigator"
  group: completed
