
# - id: doi:10.1093/bioinformatics/btx804
#   image: images/publications/bioinformatics_cover.jpeg
#   buttons:
#     - type: source
#       text: Source Code
#       link: https://github.com/asntech/intervene
#   tags:
#     - open-source
#     - software


# - id: doi:10.1093/bioinformatics/btx804
#   image: images/publications/bioinformatics_cover.jpeg
#   buttons:
#     - type: source
#       text: Source Code
#       link: https://github.com/asntech/intervene
#   tags:
#     - open-source
#     - software

# some paper returned by an ORCID with a wrong title
# - id: doi:123/456
#   title: Correct Title

# some paper returned by an ORCID that you don't want to keep at all
# - id: pubmed:123456
  # remove: true